# Generated by Django 4.1.5 on 2023-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_categoria_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mantencion',
            fields=[
                ('id_mant', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='mant')),
                ('desc_mantencion', models.CharField(max_length=50, verbose_name='descuento')),
            ],
        ),
    ]
